"""Model metadata registry. Read-only lookup keyed by model name.

The snapshot file `_models_snapshot.json` is generated by
`scripts/generate_models.py` from models.dev and committed to the repo.
No runtime fetch — regenerate the snapshot when adding new models.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ModelPricing:
    input_per_1m: float
    output_per_1m: float
    cache_read_per_1m: float | None = None
    cache_write_per_1m: float | None = None


@dataclass(frozen=True)
class ModelMeta:
    model_id: str
    context_size: int
    max_output: int
    pricing: ModelPricing | None = None


DEFAULT_META = ModelMeta(
    model_id="<unknown>",
    context_size=128_000,
    max_output=4096,
    pricing=None,
)


_SNAPSHOT_PATH = Path(__file__).parent / "_models_snapshot.json"


def _load_snapshot() -> dict[str, dict]:
    if not _SNAPSHOT_PATH.exists():
        return {}
    try:
        return json.loads(_SNAPSHOT_PATH.read_text())
    except json.JSONDecodeError:
        # Corrupt snapshot — degrade gracefully to DEFAULT_META behavior
        # rather than breaking module import.
        return {}


# Loaded once at import time. Snapshot is committed and never mutates.
_SNAPSHOT: dict[str, dict] = _load_snapshot()


def _build_meta(model_id: str, entry: dict) -> ModelMeta:
    pricing_dict = entry.get("pricing")
    pricing = (
        ModelPricing(
            input_per_1m=pricing_dict.get("input_per_1m", 0.0),
            output_per_1m=pricing_dict.get("output_per_1m", 0.0),
            cache_read_per_1m=pricing_dict.get("cache_read_per_1m"),
            cache_write_per_1m=pricing_dict.get("cache_write_per_1m"),
        )
        if pricing_dict
        else None
    )
    return ModelMeta(
        model_id=model_id,
        context_size=entry.get("context_size", 0),
        max_output=entry.get("max_output", 0),
        pricing=pricing,
    )


def lookup(model_name: str) -> ModelMeta:
    """Exact match first, then longest-prefix match against snapshot keys.
    Returns DEFAULT_META if nothing matches. Never raises."""
    entry = _SNAPSHOT.get(model_name)
    if entry is not None:
        return _build_meta(model_name, entry)

    # Longest-prefix: find the snapshot key that is the longest prefix of
    # model_name. The matched prefix must end at a '-' separator (or be the
    # whole string) so we don't mislabel across token boundaries — e.g.
    # "gpt-4omg" must NOT match "gpt-4o". Example: "gpt-4o-2099-12-31" → "gpt-4o".
    best_key: str | None = None
    for key in _SNAPSHOT:
        if (model_name == key or model_name.startswith(key + "-")) \
                and (best_key is None or len(key) > len(best_key)):
            best_key = key
    if best_key is not None:
        return _build_meta(best_key, _SNAPSHOT[best_key])

    return DEFAULT_META
